// <auto-generated />
namespace WebRole1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class signals1whyy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(signals1whyy));
        
        string IMigrationMetadata.Id
        {
            get { return "202012070100238_signals1whyy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
